#! /bin/sh

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_action2      resize_size
bspc config pointer_action2      resize_corner

# Changing border color.
bspc config focused_border_color "#665c54"
bspc config normal_border_color  "#282828"

~/.config/polybar/launch.sh &
pgrep -x nm-applet > /dev/null || nm-applet --indicator &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
pgrep -x greenclip > /dev/null || greenclip daemon &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x conky > /dev/null || $HOME/.config/conky/toggle.sh &
pgrep -x nitrogen > /dev/null || nitrogen --restore &

setxkbmap -layout us,ara -option grp:alt_shift_toggle

bspc rule -a '*' state=floating
bspc rule -a Alacritty state=tiled
bspc rule -a firefox state=tiled
bspc rule -a firefox:Devtools state=floating
bspc rule -a firefox:Places state=floating
